/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicauca.parqueadero.presentacion;

/**
 *
 * @author danie
 */
public class GUICobro extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIFicha
     */
    public GUICobro() {
        initComponents();
    }
    
    public GUICobro(String placa, String Hora_salida, String total){
        initComponents();
        Jplaca.setText(placa);
        fecha_hour_salida.setText(Hora_salida);
        total_pagar.setText(total);
        
        //DESABILITAMOS LOS CAMPOS
        Jplaca.setEditable(false);
        fecha_hour_salida.setEditable(false);
        total_pagar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Jplaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecha_hour_salida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        total_pagar = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parqueadero \"El Payanés\"");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 3, 12)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Placa: ");
        jPanel2.add(jLabel2);

        Jplaca.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jPanel2.add(Jplaca);

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha y Hora de Salida: ");
        jPanel2.add(jLabel4);

        fecha_hour_salida.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jPanel2.add(fecha_hour_salida);

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Valor a pagar: ");
        jPanel2.add(jLabel6);

        total_pagar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jPanel2.add(total_pagar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jplaca;
    private javax.swing.JTextField fecha_hour_salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField total_pagar;
    // End of variables declaration//GEN-END:variables
}
